### ISSUE TITLE
Does not work on AMD GPUs

### ISSUE THREAD

**Issue by leo60228** [Strum355/mcshader-lsp#35]
![image](https://user-images.githubusercontent.com/8355305/129484968-fa7bb459-0293-4cc9-b57b-4d7742d1841a.png)

**Comment by WoMspace** [comment]
which GPU do you have? It only works on NVidia unfortunately (I'm on AMD)

**Comment by leo60228** [comment]
I'm using AMD on Linux.

**Comment by WoMspace** [comment]
well there you go. That'll be why. Strum needs someone with an AMD card to collect all of the error codes for... something... idk you'd have to ask him.

**Comment by Strum355** [comment]
I have in-progress work to log more and more properly so that someone can provide me with the output from AMD, which is quite different to NVidia (and who knows about Intel but idk if Im gonna support that). In the meantime, someone could post the AMD output that someone in the ShaderLabs Discord had sent into my channel under this issue, would probably speed up the process :slightly_smiling_face:

**Comment by WoMspace** [comment]
I think this is what you mean? It's before the issue was created, but it's the only relevant message in the entire channel that I can find.

> Using OpenGL device AMD 4.6 (Core Profile) Mesa 20.3.4 Radeon RX 580 Series (POLARIS10, DRM 3.40.0, 5.10.25-1-lts, LLVM 11.1.0)
root of project is "/home/me/Minecraft/Main/shaderpacks/a thing"
finished building project include graph
{"mcglsl": Object({})}
ancestors for "/home/me/Minecraft/Main/shaderpacks/a thing/shaders/programs/post.vsh":
    ["/home/me/Minecraft/Main/shaderpacks/a thing/shaders/world0/final.vsh", "/home/me/Minecraft/Main/shaderpacks/a thing/shaders/world0/deferred.vsh"]
DIAGNOSTICS:
{Url { scheme: "file", host: None, port: None, path: "/home/me/Minecraft/Main/shaderpacks/a%20thing/shaders/world0/deferred.vsh", query: None, fragment: None }: [], Url { scheme: "file", host: None, port: None, path: "/home/me/Minecraft/Main/shaderpacks/a%20thing/shaders/world0/final.vsh", query: None, fragment: None }: [], Url { scheme: "file", host: None, port: None, path: "/home/me/Minecraft/Main/shaderpacks/a%20thing/shaders/programs/post.vsh", query: None, fragment: None }: [], Url { scheme: "file", host: None, port: None, path: "/home/me/Minecraft/Main/shaderpacks/a%20thing/shaders/world0/dim_id.glsl", query: None, fragment: None }: []}
document link file: "/home/me/Minecraft/Main/shaderpacks/a thing/shaders/programs/post.vsh"
links: []

**Comment by Strum355** [comment]
Thats logs from the language server itself, someone posted the actual output from the AMD glsl compile stage, maybe from the same person that sent that in?

**Comment by WoMspace** [comment]
I can't see anything at all even remotely like that, except a message from you celebrating shader disassembly

**Comment by Strum355** [comment]
Gonna close this issue for #38 instead
