### ISSUE TITLE
Build for M1 Macs

### ISSUE THREAD

**Issue by WoMspace** [Strum355/mcshader-lsp#36]
Plugin fails to load on arm64 macOS due to no compatible binaries

**Comment by Strum355** [comment]
Im going to need someone to try this out as I dont have an M1 Mac myself:

1. Download and install this file in VSCode: https://github.com/Strum355/mcshader-lsp/suites/4812214989/artifacts/135431046
Heres an instructional screenshot on how to do that:
![image](https://user-images.githubusercontent.com/18282288/147892114-f72dec4a-6ea3-4e8f-856b-afeb2d293731.png)

2. In your settings (after installing the VSIX file and reloading VSCode), enable the "skip bootstrap" flag
![image](https://user-images.githubusercontent.com/18282288/147892225-cee3a09b-a77f-4962-a7fc-c0f6bbb823f1.png)


3. Next, youre going to want to download and move a test build for aarch64-apple-darwin to the extension storage folder (example link: https://github.com/Strum355/mcshader-lsp/suites/4812214993/artifacts/135431741)
You can find where to put it by checking where the extension storage folder is on startup by opening a shader file. Make sure the file is called `mcshader-lsp`:
![image](https://user-images.githubusercontent.com/18282288/147892165-7aed1a45-836c-453e-95db-fb1f6bde0c10.png)
I'll probably change this sometime to take an arbitrary path to the binary instead of having to move it specifically to there /shrug

4. Reload VSCode and see what happens I guess? No idea if :heavy_check_mark: or :boom:

**Comment by WoMspace** [comment]
Still got errors, this is the output for Minecraft Shaders. If there are any other logs you want, let me know where they are.

INFO  [1/3/2022, 9:22:26 AM]: working with state { serverVersion: undefined }
INFO  [1/3/2022, 9:22:26 AM]: skipping language server bootstrap
INFO  [1/3/2022, 9:22:26 AM]: starting language server...
INFO  [1/3/2022, 9:22:26 AM]: server receiving events for file glob:
	 **/*.{.fsh,.vsh,.gsh,.glsl}
INFO  [1/3/2022, 9:22:26 AM]: running with binary at path:
	 /Users/alex/Library/Application Support/Code/User/globalStorage/strum355.vscode-mc-shader/mcshader-lsp

**Comment by Strum355** [comment]
In the Output tab, are there logs for Minecraft Shaders Language Server? Should be a separate entry in the dropdown

**Comment by WoMspace** [comment]
here:
[Error - 2:03:54 PM] Starting client failed
Launching server using command /Users/alex/Library/Application Support/Code/User/globalStorage/strum355.vscode-mc-shader/mcshader-lsp failed.

that's all I'm afraid

**Comment by Strum355** [comment]
Had someone else try it out and they had the same issue until they ran `chmod +x` on the binary, and then it should run 👍 lemme know how that goes and if theres any more issues further down the path

**Comment by WoMspace** [comment]
sweet yes it works, many thanks!

**Comment by Strum355** [comment]
Id imagine linting doesn't work because its neither AMD nor Nvidia GPU, we have to have different codepaths for different vendors because the output format is completely different for each. Once it has the capability to log debug info we can try making it work for M1 there too

**Comment by WoMspace** [comment]
yes you're not wrong, but given I'm used to AMD without linting, it still does everything else (include trees etc.)
